# Generated by Django 4.2.30 on 2026-09-22 08:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BiometricAccessLog",
            fields=[
                ("subject_model", models.CharField(max_length=64)),
                ("subject_id", models.CharField(db_index=True, max_length=64)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("actor", models.CharField(max_length=64)),
                ("purpose", models.CharField(max_length=32)),
                ("template_ids", models.JSONField(default=list)),
                ("at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "biometric_access_log",
            },
        ),
        migrations.CreateModel(
            name="BiometricConsent",
            fields=[
                ("subject_model", models.CharField(max_length=64)),
                ("subject_id", models.CharField(db_index=True, max_length=64)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("modality", models.CharField(max_length=16)),
                ("granted", models.BooleanField()),
                ("recorded_by", models.CharField(max_length=64)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("note", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "biometric_consent",
            },
        ),
        migrations.CreateModel(
            name="BiometricErasure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subject_model", models.CharField(max_length=64)),
                ("subject_id", models.CharField(db_index=True, max_length=64)),
                ("modalities", models.JSONField(default=list)),
                (
                    "erased",
                    models.JSONField(
                        default=dict, help_text="Counts of rows erased per modality."
                    ),
                ),
                ("reason", models.CharField(max_length=32)),
                ("erased_by", models.CharField(max_length=64)),
                ("erased_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "biometric_erasure",
            },
        ),
        migrations.CreateModel(
            name="BiometricRetentionPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("template_retention_days", models.IntegerField(blank=True, null=True)),
                ("purge_enabled", models.BooleanField(default=False)),
                (
                    "active_template_retention_days",
                    models.IntegerField(blank=True, null=True),
                ),
                ("purge_active_enabled", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "biometric_retention_policy",
            },
        ),
        migrations.CreateModel(
            name="BiometricVerification",
            fields=[
                ("subject_model", models.CharField(max_length=64)),
                ("subject_id", models.CharField(db_index=True, max_length=64)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("modality", models.CharField(max_length=16)),
                ("score", models.FloatField(blank=True, null=True)),
                ("threshold", models.FloatField()),
                ("verified", models.BooleanField()),
                (
                    "origin",
                    models.CharField(
                        choices=[("server", "server"), ("device", "device")],
                        default="server",
                        max_length=8,
                    ),
                ),
                ("fallback", models.BooleanField(default=False)),
                ("context", models.JSONField(blank=True, default=dict)),
                ("device_id", models.CharField(blank=True, default="", max_length=255)),
                ("actor", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "biometric_verification",
                "indexes": [
                    models.Index(
                        fields=["subject_model", "subject_id", "modality"],
                        name="biometric_v_subject_60971c_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BiometricTemplate",
            fields=[
                ("subject_model", models.CharField(max_length=64)),
                ("subject_id", models.CharField(db_index=True, max_length=64)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("modality", models.CharField(max_length=16)),
                ("position", models.CharField(blank=True, default="", max_length=16)),
                (
                    "kind",
                    models.CharField(
                        help_text='"embedding" or "template"', max_length=16
                    ),
                ),
                ("vector", models.JSONField(blank=True, null=True)),
                ("template", models.BinaryField(blank=True, null=True)),
                ("template_iso", models.BinaryField(blank=True, null=True)),
                ("encrypted", models.BooleanField(default=False)),
                ("quality", models.FloatField(blank=True, null=True)),
                ("provider", models.CharField(max_length=64)),
                ("model_name", models.CharField(max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("validity_from", models.DateTimeField(auto_now_add=True)),
                (
                    "validity_to",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "biometric_template",
                "indexes": [
                    models.Index(
                        fields=["modality", "provider", "model_name", "validity_to"],
                        name="biometric_template_gallery_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="biometrictemplate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("validity_to__isnull", True)),
                fields=(
                    "subject_model",
                    "subject_id",
                    "modality",
                    "position",
                    "provider",
                    "model_name",
                ),
                name="biometric_template_unique_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="biometricretentionpolicy",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("purge_enabled", True), _negated=True),
                    ("template_retention_days__isnull", False),
                    _connector="OR",
                ),
                name="biometric_retention_policy_requires_days",
            ),
        ),
        migrations.AddConstraint(
            model_name="biometricretentionpolicy",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("purge_active_enabled", True), _negated=True),
                    ("active_template_retention_days__isnull", False),
                    _connector="OR",
                ),
                name="biometric_retention_policy_active_requires_days",
            ),
        ),
        migrations.AddIndex(
            model_name="biometricconsent",
            index=models.Index(
                fields=["subject_model", "subject_id", "modality"],
                name="biometric_c_subject_c04d54_idx",
            ),
        ),
    ]
