# Generated by Django 4.2.30 on 2026-09-27 23:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("biometric", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="biometrictemplate",
            name="quality_verdict",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="biometricverification",
            name="impersonation_evidence",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="biometricverification",
            name="impersonation_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="biometricverification",
            name="impersonation_status",
            field=models.CharField(blank=True, default="", max_length=8),
        ),
        migrations.AddField(
            model_name="biometricverification",
            name="impersonation_subject_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="biometricverification",
            name="impersonation_subject_model",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="biometricverification",
            name="impersonation_suspected",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="biometricverification",
            name="risk_profile",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.CreateModel(
            name="BiometricAuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sequence", models.BigIntegerField(unique=True)),
                ("action", models.CharField(max_length=48)),
                ("actor", models.CharField(blank=True, default="", max_length=64)),
                (
                    "subject_model",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "subject_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                ("modality", models.CharField(blank=True, default="", max_length=16)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("prev_hash", models.CharField(max_length=64, unique=True)),
                ("hash", models.CharField(max_length=64)),
            ],
            options={
                "db_table": "biometric_audit_event",
                "ordering": ("sequence",),
                "indexes": [
                    models.Index(
                        fields=["action", "subject_model", "subject_id", "created_at"],
                        name="biometric_audit_subject_idx",
                    ),
                    models.Index(
                        fields=["actor", "action", "created_at"],
                        name="biometric_audit_actor_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BiometricAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rule_kind", models.CharField(max_length=48)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                        ],
                        max_length=8,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("dedupe_key", models.CharField(max_length=200)),
                (
                    "subject_model",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "subject_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("RESOLVED", "Resolved"),
                        ],
                        default="NEW",
                        max_length=16,
                    ),
                ),
                ("occurrences", models.PositiveIntegerField(default=1)),
                (
                    "triggered_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "acknowledged_by",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "resolved_by",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_note", models.TextField(blank=True, default="")),
                (
                    "trigger_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="biometric.biometricauditevent",
                    ),
                ),
            ],
            options={
                "db_table": "biometric_alert",
                "ordering": ("-triggered_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["state", "-triggered_at"],
                        name="biometric_alert_state_idx",
                    ),
                    models.Index(
                        fields=["rule_kind", "dedupe_key"],
                        name="biometric_alert_key_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="biometricalert",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state__in", ["NEW", "ACKNOWLEDGED"])),
                fields=("rule_kind", "dedupe_key"),
                name="biometric_alert_one_open_per_key",
            ),
        ),
    ]
