# Generated by Django 4.2.30 on 2026-09-28 00:15

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("biometric", "0002_quality_risk_impersonation_audit"),
    ]

    operations = [
        migrations.CreateModel(
            name="BiometricAuditChainCheck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "checked_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("checked_by", models.CharField(blank=True, default="", max_length=64)),
                ("ok", models.BooleanField()),
                ("checked", models.BigIntegerField()),
                ("head_sequence", models.BigIntegerField()),
                ("head_hash", models.CharField(max_length=64)),
                (
                    "divergence_kind",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                ("divergence_sequence", models.BigIntegerField(blank=True, null=True)),
                ("divergence_detail", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "biometric_audit_chain_check",
                "ordering": ("-checked_at", "-id"),
            },
        ),
        migrations.AddField(
            model_name="biometricverification",
            name="impersonation_skip_reason",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
