# Generated by Django 4.2.30 on 2026-09-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biometric", "0003_audit_chain_check_probe_skip_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="biometricverification",
            name="template_skip_reason",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
