# Generated by Django 4.2.30 on 2026-09-28 08:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("biometric", "0004_verification_template_skip_reason"),
    ]

    operations = [
        migrations.CreateModel(
            name="BiometricMultimodalDecision",
            fields=[
                ("subject_model", models.CharField(max_length=64)),
                ("subject_id", models.CharField(db_index=True, max_length=64)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        help_text='"accept", "review" or "reject"', max_length=8
                    ),
                ),
                ("score", models.FloatField(blank=True, null=True)),
                ("reasons", models.JSONField(blank=True, default=list)),
                (
                    "risk_profile",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("modalities", models.JSONField(blank=True, default=list)),
                ("verification_ids", models.JSONField(blank=True, default=list)),
                ("fallback", models.BooleanField(default=False)),
                ("device_id", models.CharField(blank=True, default="", max_length=255)),
                ("actor", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "biometric_multimodal_decision",
                "indexes": [
                    models.Index(
                        fields=["subject_model", "subject_id", "created_at"],
                        name="biometric_mm_decision_subj_idx",
                    )
                ],
            },
        ),
    ]
