# Generated by Django 4.2.28 on 2026-03-07 14:24

from django.db import migrations, models

from biometric_verification.legacy import HAS_INSUREE


class Migration(migrations.Migration):

    dependencies = [
        ('biometric_verification', '0003_add_embedding_metadata'),
    ]

    # No-op when insuree isn't installed: BiometricEmbedding doesn't exist (0001 was a no-op).
    operations = (
        [
            migrations.AddField(
                model_name='biometricembedding',
                name='metadata',
                field=models.JSONField(blank=True, default=dict, help_text='Complete configuration used to compute this embedding (detector_backend, enforce_detection, etc.).'),
            ),
        ]
        if HAS_INSUREE
        else []
    )
